let _env = process.env;

if (!_env.REACT_APP_API_URL) {
  _env = window._env;
}

export default {
  API_ADDRESS: _env.REACT_APP_API_URL,
  WS_ADDRESS: _env.REACT_APP_WS_URL,
  NODE_URL: _env.REACT_APP_NODE_URL,
  HYDRO_PROXY_ADDRESS: _env.REACT_APP_HYDRO_PROXY_ADDRESS,
  HYDRO_TOKEN_ADDRESS: _env.REACT_APP_HYDRO_TOKEN_ADDRESS,
  WETH_TOKEN_ADDRESS: _env.REACT_APP_WETH_TOKEN_ADDRESS,
  NETWORK_ID: _env.REACT_APP_NETWORK_ID,
  DAI_PRICE_IN_DOLLAR: _env.REACT_APP_DAI_PRICE_IN_DOLLAR,
  HOT_PRICE_IN_DOLLAR: _env.REACT_APP_HOT_PRICE_IN_DOLLAR,
  WETH_PRICE_IN_DOLLAR: _env.REACT_APP_WETH_PRICE_IN_DOLLAR,
  COIN_BASE_API_ADDRESS: _env.REACT_APP_COIN_VASE_API_ADDRESS,
  COIN_BASE_API_KEY: _env.REACT_APP_COIN_BASE_API_KEY,
};
